<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>SCP-SL-Auto-Joiner.Companion</AssemblyName>
    <RootNamespace>SCP.SL.AutoJoiner.Companion</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System.Web.Extensions" />
    <Reference Include="Assembly-CSharp" HintPath="$(SL_REFERENCES)\Assembly-CSharp.dll" />
    <Reference Include="LabAPI" HintPath="$(SL_REFERENCES)\LabAPI.dll" />
  </ItemGroup>
</Project>
