const steps = [['play', 'Play button'], ['servers_tab', 'Servers tab'], ['internet_tab', 'Internet tab'], ['direct_connect', 'Direct Connect'], ['ip_field', 'IP:port field'], ['connect_button', 'Connect button']];
let state = { calibrated: false, servers: [], points: {} }, calIndex = 0, detected = null;
const $ = id => document.getElementById(id);
const api = () => window.pywebview && window.pywebview.api;
function openView(name) { document.querySelectorAll('.view').forEach(view => view.classList.toggle('hidden', view.id !== `view-${name}`)); document.querySelectorAll('.nav').forEach(nav => { const active = nav.dataset.view === name; nav.classList.toggle('active', active); active ? nav.setAttribute('aria-current', 'page') : nav.removeAttribute('aria-current'); }); }
document.querySelectorAll('.nav').forEach(nav => nav.addEventListener('click', () => openView(nav.dataset.view)));
function log(text, muted = false) { const line = document.createElement('div'); line.className = `log-line${muted ? ' muted' : ''}`; line.textContent = text; $('log').prepend(line); }
function toast(text) { $('toast').textContent = text; $('toast').classList.add('show'); setTimeout(() => $('toast').classList.remove('show'), 3500); }
function render() { $('servers').innerHTML = state.servers.map(server => `<option value="${escapeHtml(server)}"></option>`).join(''); $('topState').textContent = state.calibrated ? 'CALIBRATED' : 'SETUP REQUIRED'; $('setupNotice').hidden = state.calibrated; showCal(); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function showCal() { if (calIndex >= steps.length) { $('calTitle').textContent = 'Calibration complete'; $('calText').textContent = 'This computer is ready for background joining.'; $('calCount').textContent = '6 / 6'; $('calBar').style.width = '100%'; return; } const [, title] = steps[calIndex]; $('calTitle').textContent = `Step ${calIndex + 1} of 6 · ${title}`; $('calCount').textContent = `${calIndex} / 6`; $('calBar').style.width = `${calIndex / steps.length * 100}%`; $('calText').textContent = `Hover your mouse over SCP:SL’s ${title}, then capture the position. Do not click the game itself.`; }
async function capturePoint() { if (!api() || calIndex >= steps.length) return; const position = await api().get_cursor(); if (!position) return toast('Could not read the mouse position.'); state.points[steps[calIndex][0]] = position; calIndex++; if (calIndex === steps.length) { state = await api().save_calibration(state.points); toast('Calibration saved for this computer.'); } showCal(); render(); }
async function startJoin() { const name = $('server').value.trim(); if (!name) return toast('Choose or type a saved server first.'); if (!state.calibrated) return toast('Calibrate this computer first.'); setRunning(true); log(`Starting queue for ${name}`); if (!await api().start_join(name)) setRunning(false); }
async function stopJoin() { if (api()) await api().stop_join(); log('Stop requested. Finishing the current input safely…', true); }
async function beginRemember() { if (!api()) return; $('rememberButton').textContent = 'Stop watching'; $('rememberButton').onclick = stopRemember; setFeed('WATCHING'); log('Watching Player.log. Join a server normally now.'); toast('Join a server normally in SCP:SL.'); await api().begin_remember(); }
async function stopRemember() { if (api()) await api().stop_remember(); $('rememberButton').textContent = 'Remember a server'; $('rememberButton').onclick = beginRemember; setFeed('IDLE'); log('Server watcher stopped.', true); }
function setFeed(text) { $('feedState').textContent = text; }
function setRunning(running) { $('startButton').disabled = running; $('stopButton').hidden = !running; $('headerBadge').classList.toggle('running', running); $('headerBadge').querySelector('span').textContent = running ? 'Running' : 'Ready'; setFeed(running ? 'RUNNING' : 'IDLE'); if (!running) $('topState').textContent = state.calibrated ? 'CALIBRATED' : 'SETUP REQUIRED'; }
function backendStatus(text, running) { if (text) log(text); if (running !== undefined) setRunning(running); }
function backendFinished(result) { setRunning(false); log(`Finished: ${result}`); toast(result === 'success' ? 'Joined successfully.' : `Run finished: ${result}.`); }
function serverDetected(ip, port) { detected = { ip, port }; $('dialogAddress').textContent = `${ip}:${port}`; $('serverName').value = ''; $('dialog').hidden = false; $('serverName').focus(); }
function closeDialog() { detected = null; $('dialog').hidden = true; }
async function saveDetectedServer() { const name = $('serverName').value.trim(); if (!name || !detected || !api()) return toast('Enter a name first.'); state = await api().save_server(name, detected.ip, detected.port); closeDialog(); render(); $('server').value = name; toast('Server saved.'); }
window.status = backendStatus; window.finished = backendFinished; window.backendStatus = backendStatus; window.backendFinished = backendFinished;
window.addEventListener('pywebviewready', () => api().get_state().then(next => { state = next; render(); }));
document.addEventListener('keydown', event => { if (event.key === 'Escape' && !$('dialog').hidden) closeDialog(); });
